### PR TITLE
Make heap.c assignment operator less ambiguous

### LINKED ISSUE #113: src/nvidia/src/kernel/gpu/mem_mgr/heap.c:1607: unclear coding ?
Static analyser cppcheck says:

src/nvidia/src/kernel/gpu/mem_mgr/heap.c:1607:69: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]

Source code is

           currentBankInfo = (currentBankInfo & BANK_MEM_GROW_DOWN ? MEM_GROW_DOWN : MEM_GROW_UP);

Presumably

           currentBankInfo = (currentBankInfo & BANK_MEM_GROW_DOWN) ? MEM_GROW_DOWN : MEM_GROW_UP;

was intended.

### PR DESCRIPTION
**Pull request by jareklupinski**
Fixes #113

### CODE REVIEW

**Comment by jareklupinski** [comment]
> Hello, and thank you for your interest and contribution.
> 
> Please note that the currently proposed change actually changes the behavior of the code and as a result `currentBankInfo` will always have the value of 0 after it executes.
> 
> If you feel the code is particularly confusing due to relying on operator precedence, usually the best option is to just explicitly add parentheses.

Ah, thank you @mtijanic ! I just shifted the parens :)

**Comment by aritger** [comment]
This might be a useful preference for precedence: https://en.cppreference.com/w/c/language/operator_precedence

This PR improves readability (thanks), though note we're going to put these sorts of PRs on the backburner for now, due to the volume of interest.  We've just posted a note about that: https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/CONTRIBUTING.md

**Comment by TrojanerHD** [comment]
> Fixes issue #113

@jareklupinski Next time you submit a PR that closes an issue, you might consider using [a linking keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) (in this case you would have needed to omit “issue”)

**Comment by niv** [comment]
Thank you for your interest in contributing to open-gpu-kernel-modules.

As recently explained in [CONTRIBUTING.md](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/CONTRIBUTING.md), we have decided to not accept cosmetic changes for now.

All changes going into this repository incur significant overhead on our end, and we'd like to focus our resources on executable code changes; so we have decided to close all PRs that make no code changes.

If and when this position changes, your PR will still be in the archives and revisited (as long as it's still tagged cosmetic-postponed).

Please do not feel discouraged to submit other changes! In addition, we will be happy to keep the conversation going on the Discussion boards here on GitHub, and elsewhere.

**Pull request closed without merging**
