### PR TITLE
TYPO

### PR DESCRIPTION
**Pull request by eljommys**
I fund a typo

### CODE REVIEW

**Comment by alcaparra** [comment]
It is of my personal opinion that this is a critical error. The misinterpretation of this TYPO could be fatal. Please accept this ASAP.

**Comment by Leseratte10** [comment]
People like you are part of the reason why companies are reluctant to release their products as actual open-source ...
What is the point of this PR?

**Comment by alcaparra** [comment]
@Leseratte10 You liked your own comment, lol.

**Comment by brunojcm-vgw** [comment]
as expected, this repo is full of children. nvidia has to do some bans before people can actually contribute useful things.

**Pull request closed without merging**
