### PR TITLE
Beginner's Instruction

### PR DESCRIPTION
**Pull request by cabelo**

### CODE REVIEW

**Comment by cabelo** [comment]
@mmaneetsingh is ok?

**Comment by carlosedp** [comment]
It would be good to add the requirements to compile like `build-essential` on Ubuntu, and etc.

**Comment by FunPineapple** [comment]
Beginners should learn how Git works before attempting to compile from source. If repos are responsible for distributing common and readily-available knowledge, NVIDIA might as well put guides on installing every distro in the Readme as well. The instructions already provided are not common and are unique to the kernel modules.

**Comment by cabelo** [comment]
> Beginners should learn how Git works before attempting to compile from source. If repos are responsible for distributing common and readily-available knowledge, NVIDIA might as well put guides on installing every distro in the Readme as well. The instructions already provided are not common and are unique to the kernel modules.

you are right.

**Pull request closed without merging**
