### PR TITLE
closed source

### PR DESCRIPTION
**Pull request by poopbarrel**
nvidia

### CODE REVIEW

**Comment by viriuwu** [comment]
so true

**Comment by poopbarrel** [comment]
hater

**Comment by troke12** [comment]
?

**Comment by Kuplynx** [comment]
lmao knew this would happen

**Comment by karolherbst** [comment]
> lmao knew this would happen

let's praise this very original idea

**Comment by karolherbst** [comment]
(actually, I think it might have been funny to replace it with nouveau with a "NOUVEAU RULEZ" title or something, but now I am too tired to actually do it, so I leave the idea here and will awake disappointed tomorrow, that nobody actually did this)

**Comment by Lisenaaaa** [comment]
i love it

**Comment by flyingpig233-cpu** [comment]
In Chinese to describe: 正能量

**Comment by leapofazzam123** [comment]
fuck off

**Comment by Cl-He-O** [comment]
lmao

**Pull request closed without merging**
