### PR TITLE
Collection of minor fixes to issues

### PR DESCRIPTION
**Pull request by Joshua-Ashton**

### CODE REVIEW

**Review by pranavo72bex — APPROVED** [review]

**Comment by aaronp24** [comment]
Thank you for contributing! I filed internal bug number 3643074 to track evaluating these and getting them merged.

**Comment by ryao** [comment]
@Joshua-Ashton You need to sign the CLA for Nvidia to be able to take these.

**Comment by Joshua-Ashton** [comment]
@ryao Doesn't work, just leads me to a blank page.

**Comment by aritger** [comment]
Sorry for the delays, @Joshua-Ashton.  I've finally merged your pull request.  Thank you for the fixes.

**Pull request merged**
