### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eljommys**

### CODE REVIEW

**Comment by alcaparra** [comment]
> That's an architecture name, why would that be capitalized? It's also "x86_64" and not "X86_64" ...

Incorrect. Following standard CEV-1992: "Architecture names shall be capitalized".
Please refrain from posting more ignorant comments.

**Comment by Leseratte10** [comment]
Take a look at ANY linux kernel code. i386/i486/i686, x86_64, aarch64, amd. NONE of these are capitalized anywhere. Your comments are ignorant.

**Comment by ilya-zlobintsev** [comment]
I feel bad for the NVIDIA employees that have to go through all the meme PRs and issues. It leaves a bad impression of the open-source community.

**Comment by niv** [comment]
> Take a look at ANY linux kernel code. i386/i486/i686, x86_64, aarch64, amd. NONE of these are capitalized anywhere.

This is correct.

**Pull request closed without merging**
