### PR TITLE
Remove extra whitelines

### PR DESCRIPTION
**Pull request by juanrd10**

### CODE REVIEW

**Comment by leirons** [comment]
seems useless

**Comment by juanrd10** [comment]
But it brings clarity, I deserve the merge.

**Comment by Shinyzenith** [comment]
if you're gonna submit such a useless patch, might as well rebase and squash them into 1 commit with a sane commit message.

**Comment by fastman** [comment]
> if you're gonna submit such a useless patch, might as well rebase and squash them into 1 commit with a sane commit message.

moar commit, moar fame

**Comment by niv** [comment]
Thanks for the report. All the extra whitespace will be handled in the future. Also see #79, also see internal bug 3643422.

**Pull request closed without merging**
