### PR TITLE
Remove unused variables

### PR DESCRIPTION
**Pull request by aqk**

### CODE REVIEW

**Review by samiurprapon — APPROVED** [review]
Checked, no usage of those variables

**Comment by mtijanic** [comment]
Thank you for the PR, but marking as `cosmetic-postponed` for now. Please see https://github.com/NVIDIA/open-gpu-kernel-modules/discussions/190 for details.

**Comment by mtijanic** [comment]
Thank you for the PR, but marking as `cosmetic-postponed` for now. Please see https://github.com/NVIDIA/open-gpu-kernel-modules/discussions/190 for details.

**Comment by niv** [comment]
It is likely that these variables are actually used; just not in the parts that are currently open-sourced. Some parts of the code are removed before publishing to GH. Thus, what you are looking at is more of a transformation artefact. I agree that it's not pretty.

That said:

---

Thank you for your interest in contributing to open-gpu-kernel-modules.

As recently explained in [CONTRIBUTING.md](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/CONTRIBUTING.md), we have decided to not accept cosmetic changes for now.

All changes going into this repository incur significant overhead on our end, and we'd like to focus our resources on executable code changes; so we have decided to close all PRs that make no code changes.

If and when this position changes, your PR will still be in the archives and revisited (as long as it's still tagged cosmetic-postponed).

Please do not feel discouraged to submit other changes! In addition, we will be happy to keep the conversation going on the Discussion boards here on GitHub, and elsewhere.

**Pull request closed without merging**
